spring:
  profiles: default
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MySQL
      user-name: sa
      password:
      tomcat:
        initial-size: 10
        max-wait: 10000
        max-active: 50
        max-idle: 10
        min-idle: 10
        test-on-borrow: true

mybatis:
  type-aliases-package: com.stunstun.spring.repository.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml